name: Execute notebook

on: [push]

jobs:
  update_plot:
    name: Update plot with new extreme weather data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Script and Update Plot
        run: |
          jupyter nbconvert --to script example.ipynb
      - name: Commit and Push Changes
        run: |
          git config --local user.email "tranhophilong12a4@gmail.com"
          git config --local user.name "Long"
          git commit -m "output"
          git push origin master
